### PR TITLE
httpun-types

### PR DESCRIPTION
**Pull request by ada2k**
This adds a small (~40kb) dependency on [httpun-types](https://ocaml.org/p/httpun-types/latest). This implements [rfc6585](https://datatracker.ietf.org/doc/html/rfc6585), while improving interop between H2, httpun and any other http library which wishes to use the same types; applications can depend on httpun-types and be assured all types will be consistent between different forks of httpaf.

### CODE REVIEW

**Comment by dinosaure** [comment]
Hmmhmm, we can actually keep `h1.mli` and I prefer to keep redondant tests too :+1:. Thanks for your contribution.

**Comment by ada2k** [comment]
> Hmmhmm, we can actually keep `h1.mli` and I prefer to keep redondant tests too 👍. Thanks for your contribution.

Httpun aliases Httpun_types in it's mli file:
`(** {2 Basic HTTP Types} *)

module IOVec : module type of Httpun_types.IOVec
module Version : module type of Httpun_types.Version
module Method : module type of Httpun_types.Method
module Status : module type of Httpun_types.Status
module Headers : module type of Httpun_types.Headers`
Would that be more appropriate than deleting it outright? Same with the tests.

**Comment by dinosaure** [comment]
> Would that be more appropriate than deleting it outright? Same with the tests.

Yes, it will be perfect :+1:.

**Comment by ada2k** [comment]
Pushed

**Comment by dinosaure** [comment]
Thanks!

**Pull request merged**
